development:
  sessions:
    default:
      database: locomotive_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: locomotive_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: iwantru
      hosts:
        - localhost:27017
